<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
  <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
    <RootNamespace>Middleware.API</RootNamespace>
    <AssemblyName>Middleware.API</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Middleware_Core\Middleware_Core.csproj" />
  </ItemGroup>

</Project>